-- Creating a database and a table with description values and one of then autogenerated and not null
-- table name: states with values: id INT UNIQUE autogenerated, primery key, name VARCHAR(256) not null
-- database: hbtn_0d_usa
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states (id INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL, name VARCHAR(256) NOT NULL);
