-- Creating a database and a table with description values and one of then autogenerated and not null
-- table name: cities with values: state_id INT foreign key that references to id of the states table, name VARCHAR(256) not null
-- database: hbtn_0d_usa
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (id INT PRIMARY KEY UNIQUE AUTO_INCREMENT, state_id INT NOT NULL, FOREIGN KEY (state_id) REFERENCES states(id), name VARCHAR(256) NOT NULL);
